name: namoral
description: Namoral é o App que vai te ajudar nas indecisões da sua vida

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dart_openai: ^4.0.0
  flutter_modular: ^6.0.4+1
  flutter_triple: ^3.0.0
  speech_to_text: ^6.3.0
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
